### ISSUE TITLE
Send reporter results via a connection instead of a hardcoded stat

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Bot#7]
the idea is that instead of having a weird hardcoded thing that sends things in the reporter channel the reporter channel will instead use an init command to 'subscribe' to it. 
In practise:
$connection add dead_roles

then the bot will send info such as reporter info by running $connection send dead_roles "the information" which will effectively end up being the same but much more versatile. 
This would also allow other roles to 'subscribe' to this information.

**Comment by Shepherdwhen** [comment]
Could be added to the reaper channel then too

**Comment by McTsts** [comment]
Reaper sees info the bot usually doesn't have (current role)

**Comment by Shepherdwhen** [comment]
> Reaper sees info the bot usually doesn't have (current role)

Oh reaper is current role
